### ISSUE TITLE
Nav bar needs to be fixed. 

### ISSUE THREAD

**Issue by lala010addict** [lala010addict/dance-party#18]
<img width="1163" alt="screen shot 2016-10-14 at 11 18 19 am" src="https://cloud.githubusercontent.com/assets/13490355/19398173/3410204e-9200-11e6-907a-f64786776910.png">

**Comment by vkraucunas** [comment]
i'd like to take this one.

**Comment by lala010addict** [comment]
thanks @vkraucunas
